require("../assets/js/bootstrap/bootstrap");
require("../assets/js/plugins/datatable/jquery.dataTables");
require("../assets/js/plugins/datatable/exts/dataTables.colVis.bootstrap");
require("../assets/js/plugins/datatable/exts/dataTables.colReorder");
// require("../assets/js/plugins/datatable/exts/dataTables.tableTools");
require("../assets/js/plugins/datatable/dataTables.bootstrap");
// require("./assets/js/plugins/jqgrid/jquery.jqGrid.min");
// require("./assets/js/plugins/jqgrid/i18n/grid.locale-en");
// require("./assets/js/plugins/jqgrid/jquery.jqGrid.fluid");
require("../assets/js/plugins/bootstrap-datepicker/bootstrap-datepicker");
require("../assets/js/plugins/daterangepicker/daterangepicker");
require("../assets/js/plugins/bootstrap-multiselect/bootstrap-multiselect");
require("../assets/js/plugins/stat/flot/jquery.flot");
// require("../assets/js/plugins/stat/flot/jquery.flot.resize.min");
// require("./assets/js/king-table");
